--------------------------------------------------------
--  File created - Thursday-February-23-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROMOTION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PROMOTION" 
   (	"PROMOTIONID" VARCHAR2(60 BYTE), 
	"PROMOTIONNAME" VARCHAR2(100 BYTE), 
	"PROMOTIONDISCOUNT" NUMBER(12,3), 
	"PROMOTIONEXPIRYDATE" VARCHAR2(100 BYTE), 
	"PROMOTIONMINREQUIREDAMOUNT" NUMBER(10,5), 
	"PROMOTIONTYPE" VARCHAR2(70 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table WALLET
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."WALLET" 
   (	"USERID" VARCHAR2(80 BYTE), 
	"WALLETBALANCE" NUMBER(24,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HOTEL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."HOTEL" 
   (	"HOTELID" VARCHAR2(80 BYTE), 
	"HOTELNAME" VARCHAR2(80 BYTE), 
	"HOTELLOCATION" VARCHAR2(80 BYTE), 
	"HOTELINFO" VARCHAR2(80 BYTE), 
	"HOTELIMAGE" VARCHAR2(40 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HOTELBOOKING
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."HOTELBOOKING" 
   (	"HOTELBOOKINGID" VARCHAR2(70 BYTE), 
	"HOTELID" VARCHAR2(70 BYTE), 
	"USERID" VARCHAR2(70 BYTE), 
	"ROOMNO" NUMBER(10,0), 
	"HOTELCHECKINDATE" DATE, 
	"HOTELCHECKOUTDATE" DATE, 
	"STAYDURATION" NUMBER(10,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HOTELROOM
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."HOTELROOM" 
   (	"HOTELID" VARCHAR2(80 BYTE), 
	"HOTELROOMNO" NUMBER(10,0), 
	"HOTELROOMTYPE" VARCHAR2(80 BYTE), 
	"HOTELROOMPRICE" NUMBER(10,2), 
	"HOTELROOMSTATUS" VARCHAR2(80 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MMT_USER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MMT_USER" 
   (	"USERID" VARCHAR2(70 BYTE), 
	"USERNAME" VARCHAR2(70 BYTE), 
	"USERPHONENO" NUMBER(10,0), 
	"USEREMAILID" VARCHAR2(70 BYTE), 
	"USERADDRESS" VARCHAR2(70 BYTE), 
	"USERPASSWORD" VARCHAR2(70 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FLIGHT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."FLIGHT" 
   (	"FLIGHTCOMPANYNAME" VARCHAR2(70 BYTE), 
	"FLIGHTID" VARCHAR2(70 BYTE), 
	"FLIGHTSOURCE" VARCHAR2(70 BYTE), 
	"FLIGHTDESTINATION" VARCHAR2(70 BYTE), 
	"FLIGHTDEPARTURETIME" VARCHAR2(70 BYTE), 
	"FLIGHTARRIVALTIME" VARCHAR2(70 BYTE), 
	"FLIGHTTICKETPRICE" NUMBER(10,2), 
	"AVAILABLESEATS" NUMBER(7,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FLIGHTBOOKING
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."FLIGHTBOOKING" 
   (	"FLIGHTBOOKINGID" VARCHAR2(400 BYTE), 
	"USERID" VARCHAR2(80 BYTE), 
	"FLIGHTID" VARCHAR2(40 BYTE), 
	"FLIGHTBOOKINGDATE" DATE, 
	"FLAG" VARCHAR2(40 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADMIN" 
   (	"ADMINID" VARCHAR2(70 BYTE), 
	"ADMINNAME" VARCHAR2(70 BYTE), 
	"ADMINPHONENO" NUMBER(10,0), 
	"ADMINEMAILID" VARCHAR2(70 BYTE), 
	"ADMINADDRESS" VARCHAR2(70 BYTE), 
	"ADMINPASSWORD" VARCHAR2(70 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.PROMOTION
SET DEFINE OFF;
Insert into SYSTEM.PROMOTION (PROMOTIONID,PROMOTIONNAME,PROMOTIONDISCOUNT,PROMOTIONEXPIRYDATE,PROMOTIONMINREQUIREDAMOUNT,PROMOTIONTYPE) values ('p1','flightnew',20,'31_may_2017',1000,'FLIGHT');
Insert into SYSTEM.PROMOTION (PROMOTIONID,PROMOTIONNAME,PROMOTIONDISCOUNT,PROMOTIONEXPIRYDATE,PROMOTIONMINREQUIREDAMOUNT,PROMOTIONTYPE) values ('p2','weekendSpecial',34,'23_mar_2017',1000,'HOTEL');
REM INSERTING into SYSTEM.WALLET
SET DEFINE OFF;
Insert into SYSTEM.WALLET (USERID,WALLETBALANCE) values ('Sujata',30300);
Insert into SYSTEM.WALLET (USERID,WALLETBALANCE) values ('us2',0);
REM INSERTING into SYSTEM.HOTEL
SET DEFINE OFF;
Insert into SYSTEM.HOTEL (HOTELID,HOTELNAME,HOTELLOCATION,HOTELINFO) values ('h1','Taj','mumbai','5_Star');
Insert into SYSTEM.HOTEL (HOTELID,HOTELNAME,HOTELLOCATION,HOTELINFO) values ('h2','Ramada','jaipur','5_Star');
REM INSERTING into SYSTEM.HOTELBOOKING
SET DEFINE OFF;
REM INSERTING into SYSTEM.HOTELROOM
SET DEFINE OFF;
Insert into SYSTEM.HOTELROOM (HOTELID,HOTELROOMNO,HOTELROOMTYPE,HOTELROOMPRICE,HOTELROOMSTATUS) values ('h1',101,'deluxe',4000,'avail');
Insert into SYSTEM.HOTELROOM (HOTELID,HOTELROOMNO,HOTELROOMTYPE,HOTELROOMPRICE,HOTELROOMSTATUS) values ('h2',201,'deluxe',3000,'avail');
Insert into SYSTEM.HOTELROOM (HOTELID,HOTELROOMNO,HOTELROOMTYPE,HOTELROOMPRICE,HOTELROOMSTATUS) values ('h2',202,'standard',2000,'avail');
REM INSERTING into SYSTEM.MMT_USER
SET DEFINE OFF;
Insert into SYSTEM.MMT_USER (USERID,USERNAME,USERPHONENO,USEREMAILID,USERADDRESS,USERPASSWORD) values ('us1','usn',9643232592,'user@gmail.com','sec2s','us1');
Insert into SYSTEM.MMT_USER (USERID,USERNAME,USERPHONENO,USEREMAILID,USERADDRESS,USERPASSWORD) values ('Sujata','Sujata',1234567,'sbatra@xyz.com','delhi','batra');
Insert into SYSTEM.MMT_USER (USERID,USERNAME,USERPHONENO,USEREMAILID,USERADDRESS,USERPASSWORD) values ('us2','usn2',1234567890,'sdf@gmail.com','a3sec2a','us2');
REM INSERTING into SYSTEM.FLIGHT
SET DEFINE OFF;
Insert into SYSTEM.FLIGHT (FLIGHTCOMPANYNAME,FLIGHTID,FLIGHTSOURCE,FLIGHTDESTINATION,FLIGHTDEPARTURETIME,FLIGHTARRIVALTIME,FLIGHTTICKETPRICE,AVAILABLESEATS) values ('AirIndia','f1','mumbai','chennai','05:30','07:29',2450,230);
Insert into SYSTEM.FLIGHT (FLIGHTCOMPANYNAME,FLIGHTID,FLIGHTSOURCE,FLIGHTDESTINATION,FLIGHTDEPARTURETIME,FLIGHTARRIVALTIME,FLIGHTTICKETPRICE,AVAILABLESEATS) values ('SpiceJet','f2','delhi','bangalore','08:20','10:00',2000,34);
REM INSERTING into SYSTEM.FLIGHTBOOKING
SET DEFINE OFF;
Insert into SYSTEM.FLIGHTBOOKING (FLIGHTBOOKINGID,USERID,FLIGHTID,FLIGHTBOOKINGDATE,FLAG) values ('10981','Sujata','f2',to_date('13-FEB-17','DD-MON-RR'),'true');
REM INSERTING into SYSTEM.ADMIN
SET DEFINE OFF;
Insert into SYSTEM.ADMIN (ADMINID,ADMINNAME,ADMINPHONENO,ADMINEMAILID,ADMINADDRESS,ADMINPASSWORD) values ('ad1','adn',7597188775,'email@gmail.com','address','adp');
